name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js v22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install Dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint

      - name: Build Workspace
        run: pnpm run build

      - name: Typecheck
        run: pnpm run typecheck

      - name: Run Vitest
        run: pnpm run test
